version: '3.8'
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - '9925:9000'
    environment:
      - BASE_URL=http://localhost:9925
      - ALLOW_SIGNUP=true
      - DEFAULT_EMAIL=admin@sofia.local
      - DEFAULT_PASSWORD=$(openssl rand -base64 16 | tr -dc A-Za-z0-9 | head -c 16)
      - TZ=America/Sao_Paulo
    volumes:
      - ./mealie-data:/app/data
