name: Deploy YOLO Service (Render)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'yolo_service/**'
      - '.github/workflows/deploy-yolo-render.yml'
  workflow_dispatch: {}

jobs:
  trigger-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "RENDER_DEPLOY_HOOK_URL not set as repo secret" >&2
            exit 1
          fi
          curl -s -X POST "$RENDER_DEPLOY_HOOK_URL" -H 'Accept: application/json' | jq '.' || true

